version: 2.1

orbs:
  tools: replikativ/clj-tools@0

jobs:
  build:
    executor: tools/clojurecli
    parameters:
      build_cljs:
        type: boolean
        default: false
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: clean
          command: clojure -T:build clean
      - run:
          name: jar
          command: clojure -T:build jar
      - when:
          condition: <<parameters.build_cljs>>
          steps:
            - run:
                name: compile_cljs
                command: npx shadow-cljs compile ci
                no_output_timeout: 5m
      - persist_to_workspace:
          root: /home/circleci/
          paths:
            - .m2
            - replikativ

workflows:
  build-test-and-deploy:
    jobs:
      - tools/setup:
          context: clojars-deploy
          setup_cljs: false
      - build:
          context: clojars-deploy
          build_cljs: false
          requires:
            - tools/setup
      - tools/format:
          context: clojars-deploy
          requires:
            - tools/setup
      - tools/unittest:
          context: clojars-deploy
          requires:
            - build
      - tools/cljstest:
          context: clojars-deploy
          requires:
            - build
      - tools/deploy:
          context: clojars-deploy
          filters:
            branches:
              only: main
          requires:
            - tools/format
            - tools/unittest
            - tools/cljstest
      - tools/release:
          context:
            - github-token
          filters:
            branches:
              only: main
          requires:
            - tools/deploy
