version: 2.1

orbs:
  tools: replikativ/clj-tools@0

jobs:
  build:
    executor: tools/clojurecli
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: clean
          command: clojure -T:build clean
      - run:
          name: jar
          command: clojure -T:build jar
      - run:
          name: compile_cljs
          command: npx shadow-cljs compile ci
          no_output_timeout: 5m
      - persist_to_workspace:
          root: /home/circleci/
          paths:
            - .m2
            - replikativ

workflows:
  build-test-and-deploy:
    jobs:
      - tools/setup:
          context: dockerhub-deploy
      - build:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/format:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/unittest:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/deploy:
          context:
            - dockerhub-deploy
            - clojars-deploy
          filters:
            branches:
              only: main
          requires:
            - build
            - tools/format
            - tools/unittest
      - tools/release:
          context:
            - github-token
            - dockerhub-deploy
          filters:
            branches:
              only: main
          requires:
            - tools/deploy
